# Generated by Django 4.0.2 on 2022-05-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.ForeignKey(default='?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.catagory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
