# Generated by Django 4.0.2 on 2022-05-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecatagory',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.catagory'),
        ),
    ]
