# Generated by Django 4.0.2 on 2022-05-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='host',
            new_name='user',
        ),
    ]
