# Generated by Django 4.0.2 on 2022-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'PROCESS'), ('shepping', 'SHEPPING'), ('done', 'DONE')], default='process', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
