# Generated by Django 4.0.2 on 2022-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reveaws'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveaws',
            name='taitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
