# Generated by Django 4.0.2 on 2022-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reveaws_taitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveaws',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
