# Generated by Django 4.0.2 on 2022-05-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_flashdela'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashDela',
            new_name='FlashDeal',
        ),
    ]
