# Generated by Django 4.0.2 on 2022-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_flashdela_flashdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdeal',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
