# Generated by Django 4.0.2 on 2022-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_flashdeal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdeal',
            name='background',
            field=models.ImageField(null=True, upload_to='flash/'),
        ),
    ]
