# Generated by Django 4.0.2 on 2022-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
        migrations.RemoveField(
            model_name='reveaws',
            name='product',
        ),
        migrations.AddField(
            model_name='reveaws',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
    ]
