# Generated by Django 4.0.2 on 2022-05-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastname',
        ),
    ]
