# Generated by Django 4.0.2 on 2022-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quintity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.BooleanField(default=False),
        ),
    ]
