# Generated by Django 4.0.2 on 2022-05-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_quintity_order_size_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniverselColor',
        ),
        migrations.DeleteModel(
            name='UniverselSize',
        ),
        migrations.RemoveField(
            model_name='reveaws',
            name='product',
        ),
        migrations.AddField(
            model_name='reveaws',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
    ]
