# Generated by Django 4.0.2 on 2022-05-07 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_universelcolor_delete_universelsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.RemoveField(
            model_name='reveaws',
            name='product',
        ),
        migrations.AddField(
            model_name='reveaws',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
    ]
