# Generated by Django 4.0.2 on 2022-05-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_product_info_remove_reveaws_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reveaws',
            name='product',
        ),
        migrations.AddField(
            model_name='reveaws',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
    ]
