# Generated by Django 4.0.2 on 2022-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_reveaws_product_reveaws_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveaws',
            name='total',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
