# Generated by Django 4.0.2 on 2022-05-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_order_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reveaws',
            options={'ordering': ['total']},
        ),
    ]
