# Generated by Django 4.0.2 on 2022-05-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_order_total_totla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Totla',
        ),
    ]
