# Generated by Django 4.0.2 on 2022-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_delete_totla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trend/')),
            ],
        ),
    ]
