# Generated by Django 4.0.2 on 2022-06-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_trendcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendcover',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
