# Generated by Django 4.0.2 on 2022-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_trendcover_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DeleveryPrice',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
