# Generated by Django 4.2 on 2023-04-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_product_images_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
