# Generated by Django 4.2 on 2023-04-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
