# Generated by Django 5.1.7 on 2025-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveaws',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
