# Generated by Django 5.1.7 on 2025-03-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_reveaws_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coversell',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coversell',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='coversell',
            name='taitle',
        ),
    ]
