# Generated by Django 5.2 on 2025-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_coversell_price_remove_coversell_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coversell',
            name='mobile_image',
            field=models.ImageField(null=True, upload_to='coversell/'),
        ),
    ]
