# Generated by Django 5.2 on 2025-04-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_coversell_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(null=True, upload_to='featured/')),
                ('taitle', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.catagory')),
            ],
        ),
    ]
