# Generated by Django 5.2 on 2025-04-20 12:06

from django.db import migrations
from django.utils.text import slugify

def generate_unique_slug(apps, title, product_id=None):
    Product = apps.get_model('main', 'Product')
    slug = slugify(title)
    unique_slug = slug
    counter = 1
    while Product.objects.filter(slug=unique_slug).exclude(id=product_id).exists():
        unique_slug = f"{slug}-{counter}"
        counter += 1
    return unique_slug

def populate_slugs(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.slug = generate_unique_slug(apps, product.taitle, product.id)
        product.save()

def reverse_populate_slugs(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    Product.objects.all().update(slug='')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_product_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
