# Generated by Django 5.2 on 2025-04-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_productreview_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='review_token',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
    ]
