# Generated by Django 5.2 on 2025-04-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_order_status_cartorder_cartorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='home_address2',
        ),
    ]
