# Generated by Django 5.2 on 2025-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_remove_cartorder_companyname_remove_cartorder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
