# Generated by Django 5.2 on 2025-04-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='companyname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='home_address2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
