# Generated by Django 5.2 on 2025-04-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_order_companyname_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='delivery_location',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('outside', 'Outside Dhaka')], default='dhaka', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('outside', 'Outside Dhaka')], default='dhaka', max_length=10),
        ),
    ]
